apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot-app-local
  namespace: springboot-local
  labels:
    app: java-springboot-app
    version: local
    environment: local
spec:
  # Single replica for local development
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: java-springboot-app
      environment: local
  template:
    metadata:
      labels:
        app: java-springboot-app
        version: local
        environment: local
    spec:
      containers:
      - name: java-springboot-app
        # Use local image for minikube/kind
        image: java-springboot-docker-k8s-example:local
        # Use IfNotPresent for local development to avoid pulling from registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local, dev"
        - name: SERVER_PORT
          value: "8080"
        - name: MANAGEMENT_PORT
          value: "8080"
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: spring.application.name
        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: app.environment
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: logging.level
        - name: DEBUG_ENABLED
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: app.debug-enabled
        - name: HEALTH_MEMORY_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: app.health.memory-threshold
        - name: HEALTH_DISK_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: app.health.disk-threshold
        - name: EXTERNAL_SERVICE_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: app.external-service.timeout
        - name: EXTERNAL_SERVICE_RETRY_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: app.external-service.retry-attempts
        - name: MANAGEMENT_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: app-config-local
              key: management.endpoints
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 20
          successThreshold: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
